/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Status */
        patch: operations["patch_status_api_jobs__job_id__status_patch"];
        trace?: never;
    };
    "/api/jobs/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Manual Job
         * @description Insert a manually-entered job, score it, and return the detail blob.
         *
         *     `source` is hard-wired to "manual" — the DTO has no source field so the
         *     user cannot override it. `stable_job_id` makes repeated POSTs of the
         *     same (company, role, url) idempotent: the second POST upserts the same
         *     row instead of creating a duplicate.
         */
        post: operations["add_manual_job_api_jobs_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/tailor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tailor Job
         * @description Generate a tailor sheet for one scored job.
         *
         *     Returns `{mode, ai_pending, markdown}`. When no LLM is configured we
         *     still produce the deterministic template (so the UI always has
         *     something to show) but flip `ai_pending=True` so the frontend can
         *     render the "AI integration pending" banner explicitly.
         */
        post: operations["tailor_job_api_jobs__job_id__tailor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_api_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resume */
        get: operations["get_resume_api_resume_get"];
        /** Put Resume */
        put: operations["put_resume_api_resume_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resume Pdf */
        get: operations["get_resume_pdf_api_resume_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/docx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resume Docx */
        get: operations["get_resume_docx_api_resume_docx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_settings_profile_get"];
        /** Put Profile */
        put: operations["put_profile_api_settings_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_api_settings_companies_get"];
        put?: never;
        /** Add Company */
        post: operations["add_company_api_settings_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/companies/{cid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Company */
        delete: operations["delete_company_api_settings_companies__cid__delete"];
        options?: never;
        head?: never;
        /** Update Company */
        patch: operations["update_company_api_settings_companies__cid__patch"];
        trace?: never;
    };
    "/api/settings/scoring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scoring */
        get: operations["get_scoring_api_settings_scoring_get"];
        /** Put Scoring */
        put: operations["put_scoring_api_settings_scoring_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sources */
        get: operations["get_sources_api_settings_sources_get"];
        /** Put Sources */
        put: operations["put_sources_api_settings_sources_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicationOut */
        ApplicationOut: {
            /** @default Found */
            status: components["schemas"]["ApplicationStatus"];
            /** Notes */
            notes?: string | null;
            /** Next Interview At */
            next_interview_at?: string | null;
            /** Interview Notes */
            interview_notes?: string | null;
            /** Applied At */
            applied_at?: string | null;
            /** Rejected At */
            rejected_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * ApplicationStatus
         * @enum {string}
         */
        ApplicationStatus: "Found" | "Shortlisted" | "Need Referral" | "Tailoring Resume" | "Applied" | "Recruiter Reply" | "Assessment Pending" | "Interviewing" | "Rejected" | "Archived";
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /** Llm Enabled */
            llm_enabled: boolean;
            /**
             * Llm Provider
             * @default
             */
            llm_provider: string;
            /** Notion Enabled */
            notion_enabled: boolean;
            /** Outlook Enabled */
            outlook_enabled: boolean;
            /** Gmail Enabled */
            gmail_enabled: boolean;
            /**
             * Resume Source
             * @enum {string}
             */
            resume_source: "portfolio" | "local" | "none";
        };
        /** CompanyIn */
        CompanyIn: {
            /** Name */
            name: string;
            /** Careers Url */
            careers_url?: string | null;
            /**
             * Ats Type
             * @default unknown
             */
            ats_type: string;
            /** Board Token */
            board_token?: string | null;
            /** Org Slug */
            org_slug?: string | null;
            /** Company Slug */
            company_slug?: string | null;
            /** Preferred Locations */
            preferred_locations?: string[];
            /**
             * Priority
             * @default P2
             */
            priority: string;
            /** Notes */
            notes?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        } & {
            [key: string]: unknown;
        };
        /** CompanyPatch */
        CompanyPatch: {
            /** Name */
            name?: string | null;
            /** Careers Url */
            careers_url?: string | null;
            /** Ats Type */
            ats_type?: string | null;
            /** Board Token */
            board_token?: string | null;
            /** Org Slug */
            org_slug?: string | null;
            /** Company Slug */
            company_slug?: string | null;
            /** Preferred Locations */
            preferred_locations?: string[] | null;
            /** Priority */
            priority?: string | null;
            /** Notes */
            notes?: string | null;
            /** Enabled */
            enabled?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Counts By Priority */
            counts_by_priority: {
                [key: string]: number;
            };
            /** Total Jobs */
            total_jobs: number;
            /** Last Run At */
            last_run_at?: string | null;
            /** Upcoming Interviews */
            upcoming_interviews: components["schemas"]["UpcomingInterview"][];
            /** Shortlist Top */
            shortlist_top: components["schemas"]["ScoredJobOut"][];
            /** Latest Source Stats */
            latest_source_stats?: {
                [key: string]: components["schemas"]["SourceStat"];
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Llm Enabled */
            llm_enabled: boolean;
            /** Notion Enabled */
            notion_enabled: boolean;
            /** Outlook Enabled */
            outlook_enabled: boolean;
            /** Gmail Enabled */
            gmail_enabled: boolean;
        };
        /** JobDetailOut */
        JobDetailOut: {
            job: components["schemas"]["JobOut"];
            scored?: components["schemas"]["ScoredJobOut"] | null;
            application?: components["schemas"]["ApplicationOut"] | null;
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: string;
            /** Role */
            role: string;
            /** Company */
            company: string;
            /** Url */
            url: string;
            /** Source */
            source: string;
            /** Location */
            location?: string | null;
            /** Remote Type */
            remote_type?: string | null;
            /** Posted Date */
            posted_date?: string | null;
            /** Description */
            description?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ManualJobIn */
        ManualJobIn: {
            /** Role */
            role: string;
            /** Company */
            company: string;
            /** Url */
            url: string;
            /** Location */
            location?: string | null;
            /** Description */
            description?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "P0" | "P1" | "P2" | "Ignore";
        /** ProfileIn */
        ProfileIn: {
            /** Name */
            name?: string | null;
            /** Years Of Experience */
            years_of_experience?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** ResumeIn */
        ResumeIn: {
            /** Markdown */
            markdown: string;
        };
        /** ResumeResponse */
        ResumeResponse: {
            /**
             * Md Source
             * @enum {string}
             */
            md_source: "portfolio" | "local" | "none";
            /**
             * Markdown
             * @default
             */
            markdown: string;
            /**
             * Has Pdf
             * @default false
             */
            has_pdf: boolean;
            /**
             * Has Docx
             * @default false
             */
            has_docx: boolean;
        };
        /** ScoredJobOut */
        ScoredJobOut: {
            job: components["schemas"]["JobOut"];
            /** Fit Score */
            fit_score: number;
            priority: components["schemas"]["Priority"];
            /**
             * Level Match
             * @default
             */
            level_match: string;
            /** Matched Skills */
            matched_skills?: string[];
            /** Missing Skills */
            missing_skills?: string[];
            /** Reasons */
            reasons?: string[];
            /** Risks */
            risks?: string[];
            /** Recommended Resume Variant */
            recommended_resume_variant?: string | null;
            /**
             * Next Action
             * @default
             */
            next_action: string;
            application?: components["schemas"]["ApplicationOut"] | null;
        };
        /** ScoringIn */
        ScoringIn: {
            /** Thresholds */
            thresholds?: {
                [key: string]: number;
            };
            /** Positive Keywords */
            positive_keywords?: string[];
            /** Negative Keywords */
            negative_keywords?: string[];
            /** Location Boosts */
            location_boosts?: {
                [key: string]: number;
            };
            /** Domain Boosts */
            domain_boosts?: {
                [key: string]: number;
            };
            /** Company Boosts */
            company_boosts?: {
                [key: string]: number;
            };
            /** Source Quality Boosts */
            source_quality_boosts?: {
                [key: string]: number;
            };
            /** Resume Variant Rules */
            resume_variant_rules?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Location */
            location?: string | null;
            /** Keyword */
            keyword?: string | null;
            /** Sources */
            sources?: string[] | null;
            /**
             * Use Llm
             * @default true
             */
            use_llm: boolean;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Jobs */
            jobs: components["schemas"]["ScoredJobOut"][];
            /** Source Stats */
            source_stats: {
                [key: string]: components["schemas"]["SourceStat"];
            };
            /** Ran At */
            ran_at: string;
            /** Duration Ms */
            duration_ms: number;
        };
        /** SourceStat */
        SourceStat: {
            /**
             * Fetched
             * @default 0
             */
            fetched: number;
            /**
             * Kept
             * @default 0
             */
            kept: number;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /** Error */
            error?: string | null;
        };
        /** StatusPatch */
        StatusPatch: {
            status: components["schemas"]["ApplicationStatus"];
            /** Notes */
            notes?: string | null;
            /** Next Interview At */
            next_interview_at?: string | null;
            /** Interview Notes */
            interview_notes?: string | null;
        };
        /** TailorOut */
        TailorOut: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "deterministic" | "llm";
            /** Ai Pending */
            ai_pending: boolean;
            /** Markdown */
            markdown: string;
        };
        /** UpcomingInterview */
        UpcomingInterview: {
            /** Job Id */
            job_id: string;
            /** Role */
            role: string;
            /** Company */
            company: string;
            /** Next Interview At */
            next_interview_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    capabilities_api_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                priority?: string[] | null;
                status?: string[] | null;
                company?: string | null;
                source?: string | null;
                remote_type?: string | null;
                location_contains?: string | null;
                q?: string | null;
                sort?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoredJobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_status_api_jobs__job_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_manual_job_api_jobs_manual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualJobIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tailor_job_api_jobs__job_id__tailor_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TailorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    get_resume_api_resume_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
        };
    };
    put_resume_api_resume_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_pdf_api_resume_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_resume_docx_api_resume_docx_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_profile_api_settings_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    put_profile_api_settings_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_companies_api_settings_companies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    add_company_api_settings_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_company_api_settings_companies__cid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_company_api_settings_companies__cid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scoring_api_settings_scoring_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    put_scoring_api_settings_scoring_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoringIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sources_api_settings_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    put_sources_api_settings_sources_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
