import type { JsonRecord, MissionType } from "./domain";

export const MISSION_LABELS: Record<MissionType, string> = {
  DISCOVER_JOBS: "Discover jobs", INSPECT_JOB: "Inspect job", COMPARE_RESUME: "Compare resumes", PREPARE_APPLICATION: "Prepare application", APPLY_JOB: "Prepare apply job", INSPECT_PROFILE: "Inspect profile", UPDATE_PROFILE: "Update profile", FIND_CONTACT: "Find contact", VERIFY_CONTACT: "Verify contact", REVIEW_MAIL: "Review mail", FOLLOW_UP_REVIEW: "Review follow-ups", CUSTOM: "Custom mission",
};
export const defaultConstraints: JsonRecord = {
  safety: ["READ_ONLY"], doNotSubmit: true, stopOnUnknown: true,
  rules: ["Do not submit an application without explicit human approval.", "Do not send messages or emails.", "Do not fabricate skills, employment history, contact details, or answers.", "Do not alter the selected resume.", "Stop and record any UNKNOWN or ambiguous required information.", "Record evidence and return to JobOps."],
};
type PlanStep = { title: string; instruction: string; requiresApproval: boolean };
const step = (title: string, instruction = title, requiresApproval = false): PlanStep => ({ title, instruction, requiresApproval });
export function missionTemplate(type: MissionType, target = "the selected entity") {
  const common = [step("Return to JobOps", "Open the result form and record a truthful result with evidence and any unknown questions.")];
  const plans: Record<MissionType, { goal: string; steps: PlanStep[]; safety: string[]; expectedResult: JsonRecord }> = {
    DISCOVER_JOBS: { goal: "Find recently posted jobs matching the configured criteria. Prefer official company career pages. Do not apply. Return structured job records for validation and import.", steps: [step("Read discovery criteria"), step("Search selected sources", "Search only the requested roles, locations, experience range, freshness and keyword criteria."), step("Collect and verify job records", "Retain original job URLs and descriptions; avoid duplicates and honor maximum results."), step("Return structured records", "Open /import/jobs, paste the JSON array, validate rows and import only reviewed results."), ...common], safety: ["READ_ONLY"], expectedResult: { successCriteria: ["Jobs meet the requested criteria", "No applications submitted", "Structured records include original source URLs"], jobs: [{ company: "string", title: "string", location: "string", url: "https://...", source: "COMPANY_CAREERS", postedAt: "YYYY-MM-DD or null", experienceMin: "number or null", experienceMax: "number or null", description: "string", notes: "string" }] } },
    INSPECT_JOB: { goal: `Inspect ${target} and record verified requirements, availability and any ambiguity.`, steps: [step("Open original job"), step("Inspect requirements and availability"), step("Record verified observations"), ...common], safety: ["READ_ONLY"], expectedResult: { successCriteria: ["Requirements and availability captured"], observations: "string", unknownQuestions: [] } },
    COMPARE_RESUME: { goal: `Compare the selected resume with ${target}. Record explainable keyword coverage and gaps without inventing expertise.`, steps: [step("Read job requirements"), step("Read selected resume"), step("Compare requirements", "Use factual keyword overlap and manual observations; do not call this an AI score."), ...common], safety: ["READ_ONLY"], expectedResult: { successCriteria: ["Matched and missing requirements recorded"], matchedKeywords: [], missingKeywords: [], notes: "string" } },
    PREPARE_APPLICATION: { goal: `Prepare an application for ${target} and stop before final submission.`, steps: [step("Open application page"), step("Inspect current form"), step("Fill canonical candidate details", "Use only supplied candidate information and standard answers. Treat null/UNKNOWN as unknown."), step("Upload selected resume", "Download the selected PDF without modifying it."), step("Record unknown or ambiguous questions"), step("Stop before final submission", "A human must review and explicitly approve any eventual final submission.", true), ...common], safety: ["EXTERNAL_WRITE", "USER_APPROVAL"], expectedResult: { successCriteria: ["Application ready for human review", "No final submission", "Unknown questions recorded"], applicationStage: "READY_FOR_REVIEW", unknownQuestions: [], resultUrl: "https://..." } },
    APPLY_JOB: { goal: `Prepare an application for ${target} and stop before final submission.`, steps: [step("Open application page"), step("Inspect current form"), step("Fill candidate details", "Use CandidateProfile and canonical answers only; never guess UNKNOWN values."), step("Upload selected resume", "Use the provided download link; do not modify the resume."), step("Answer standard questions", "Use canonical answers only."), step("Record unknown or ambiguous questions"), step("Stop before Submit", "Do not submit without explicit human approval. Record READY_FOR_REVIEW.", true), ...common], safety: ["EXTERNAL_WRITE", "USER_APPROVAL", "IRREVERSIBLE"], expectedResult: { successCriteria: ["Application ready for review", "Selected resume used", "No unapproved submission"], applicationStage: "READY_FOR_REVIEW", unknownQuestions: [], resultUrl: "https://..." } },
    INSPECT_PROFILE: { goal: `Inspect ${target} and record observed profile state without changing it.`, steps: [step("Open profile"), step("Inspect visible fields", "Read only; do not save edits or expose portal credentials."), step("Record observed state"), ...common], safety: ["READ_ONLY"], expectedResult: { successCriteria: ["Observed fields and inspection evidence recorded"], profileState: {} } },
    UPDATE_PROFILE: { goal: `Apply only the explicitly approved differences to ${target}. Preserve unrelated fields and record final observed state.`, steps: [step("Read approved differences"), step("Review with human", "Only changes approved in the diff may be applied.", true), step("Update explicit fields", "Do not change unrelated values or submit unknown data."), step("Record final observed state"), ...common], safety: ["EXTERNAL_WRITE", "USER_APPROVAL"], expectedResult: { successCriteria: ["Only approved differences changed", "Old and new values preserved", "Final observed state recorded"], profileState: {}, approvedFields: [] } },
    FIND_CONTACT: { goal: `Find an appropriate recruiter, hiring manager or referral contact for ${target}. Use public sources and do not message anyone.`, steps: [step("Inspect company and job"), step("Find publicly listed relevant contact"), step("Record public sources", "Never guess an email address or claim a verification that was not performed."), ...common], safety: ["READ_ONLY"], expectedResult: { successCriteria: ["Contact has a public source", "No messages sent"], contact: { name: "string", title: "string", company: "string", email: "public email or empty", linkedinUrl: "public URL or empty", source: "public source URL", verificationStatus: "UNKNOWN" } } },
    VERIFY_CONTACT: { goal: `Review verification evidence for ${target}. Do not send a verification email or contact the person.`, steps: [step("Review provided contact and sources"), step("Record actual verification evidence"), ...common], safety: ["READ_ONLY"], expectedResult: { successCriteria: ["Verification backed by recorded evidence"], verificationStatus: "UNKNOWN", source: "string" } },
    REVIEW_MAIL: { goal: "Review imported recruiting mail and proposed classifications. Confirm ambiguous messages manually; do not send, modify or delete email.", steps: [step("Open Mail review queue"), step("Compare messages with applications"), step("Review proposed updates", "Confirm each update explicitly; do not infer a stage from ambiguous mail."), ...common], safety: ["READ_ONLY"], expectedResult: { successCriteria: ["Mail classifications reviewed", "No emails sent or modified"], reviewedMessages: [] } },
    FOLLOW_UP_REVIEW: { goal: `Review next steps for ${target} and prepare a follow-up recommendation. Do not send any message.`, steps: [step("Review application timeline"), step("Review next-action date"), step("Record recommendation", "Draft notes only; sending requires separate human action."), ...common], safety: ["READ_ONLY"], expectedResult: { successCriteria: ["Recommendation and next action recorded", "No message sent"], recommendation: "string", nextActionAt: "YYYY-MM-DD or null" } },
    CUSTOM: { goal: "Complete the explicitly described task within its constraints and return an auditable result.", steps: [step("Read goal and constraints"), step("Execute approved task", "Stop on unclear instructions or unknown required information."), ...common], safety: ["READ_ONLY"], expectedResult: { successCriteria: ["Goal completed within constraints"], summary: "string", unknownQuestions: [] } },
  };
  const plan = plans[type];
  return { ...plan, title: `${MISSION_LABELS[type]}${target !== "the selected entity" ? ` · ${target}` : ""}`, constraints: { ...defaultConstraints, safety: plan.safety, ...(type === "UPDATE_PROFILE" ? { onlyApprovedDifferences: true, preserveUnrelatedFields: true } : {}) } };
}
